a1 = Artist.create(name: "Adele", bio: "Woman singer")
a2 = Artist.create(name: "Interpol", bio: "NYC band")
g1 = Genre.create(name: "Pop")
g2 = Genre.create(name: "Post Punk")
s1 = Song.create(name: "Hello", artist: a1, genre: g1)
s2 = Song.create(name: "Rolling In The Deep", artist: a1, genre: g1)
s3 = Song.create(name: "Untitled", artist: a2, genre: g2)